// 200 sujets de PFE — outils 100 % open source
// Champs : t (titre), s (stack), n (niveau), d (durée en mois)

const AI = [
  ["Détection de défauts industriels par vision par ordinateur", "PyTorch, OpenCV, Albumentations, FastAPI", "Avancé", 6],
  ["Moteur de recherche sémantique multilingue pour documents administratifs", "sentence-transformers, Qdrant, FastAPI", "Intermédiaire", 5],
  ["Reconnaissance automatique de la parole en arabe dialectal tunisien", "Whisper, Kaldi, HuggingFace Datasets", "Avancé", 6],
  ["Résumé automatique de rapports techniques longs", "Llama.cpp, LangChain, Streamlit", "Intermédiaire", 4],
  ["Segmentation d'images médicales pulmonaires", "MONAI, PyTorch, nnU-Net", "Avancé", 6],
  ["Prévision de la consommation électrique par séries temporelles", "Darts, Prophet, scikit-learn", "Intermédiaire", 5],
  ["Détection de fraude bancaire par apprentissage déséquilibré", "imbalanced-learn, XGBoost, MLflow", "Intermédiaire", 5],
  ["Classification de sentiments sur avis clients en français", "spaCy, CamemBERT, Gradio", "Débutant", 4],
  ["Génération de descriptions produit à partir d'images", "BLIP-2, PyTorch, FastAPI", "Avancé", 6],
  ["OCR de documents manuscrits scannés", "Tesseract, PaddleOCR, OpenCV", "Intermédiaire", 4],
  ["Système de recommandation hybride pour plateforme e-learning", "LightFM, Implicit, PostgreSQL", "Intermédiaire", 5],
  ["Détection d'anomalies sur capteurs IoT industriels", "PyOD, River, Kafka", "Avancé", 6],
  ["Traduction automatique français–arabe spécialisée juridique", "MarianMT, OpenNMT, SacreBLEU", "Avancé", 6],
  ["Estimation de pose humaine pour analyse sportive", "MediaPipe, OpenPose, OpenCV", "Intermédiaire", 5],
  ["Compression et quantification de modèles pour l'embarqué", "ONNX Runtime, TensorFlow Lite, Neural Compressor", "Avancé", 6],
  ["Classification de déchets par images pour tri automatisé", "PyTorch, timm, FastAPI", "Débutant", 4],
  ["Prédiction du décrochage étudiant à partir de traces d'apprentissage", "scikit-learn, SHAP, Metabase", "Intermédiaire", 5],
  ["Détection de maladies des plantes sur photos de terrain", "TensorFlow, Keras, Flutter", "Débutant", 4],
  ["Modèle de scoring crédit explicable", "LightGBM, SHAP, Streamlit", "Intermédiaire", 5],
  ["Synthèse vocale en arabe standard", "Coqui TTS, espeak-ng, Praat", "Avancé", 6],
  ["Analyse automatique de CV et appariement aux offres", "spaCy, sentence-transformers, Elasticsearch", "Intermédiaire", 5],
  ["Suivi multi-objets pour comptage de véhicules", "YOLOv8 (Ultralytics), ByteTrack, OpenCV", "Intermédiaire", 5],
  ["Détection de contenus haineux sur réseaux sociaux", "HuggingFace Transformers, Optuna, FastAPI", "Intermédiaire", 5],
  ["Apprentissage fédéré pour données de santé distribuées", "Flower, PyTorch, Docker", "Avancé", 6],
  ["Reconnaissance de langue des signes par vidéo", "MediaPipe, PyTorch, OpenCV", "Avancé", 6],
  ["Super-résolution d'images satellitaires", "Real-ESRGAN, PyTorch, Rasterio", "Avancé", 6],
  ["Prédiction de la qualité de l'air urbain", "scikit-learn, Darts, Grafana", "Intermédiaire", 4],
  ["Détection de plagiat sémantique dans les mémoires", "sentence-transformers, FAISS, FastAPI", "Intermédiaire", 5],
  ["Classification audio d'événements urbains", "torchaudio, librosa, PyTorch", "Intermédiaire", 5],
  ["Optimisation d'hyperparamètres distribuée", "Optuna, Ray Tune, MLflow", "Avancé", 6],
  ["Modèle de diffusion pour génération d'images de synthèse", "Stable Diffusion (Diffusers), PyTorch, Gradio", "Avancé", 6],
  ["Extraction d'entités nommées sur documents financiers", "spaCy, Label Studio, FastAPI", "Intermédiaire", 5],
  ["Interprétabilité des réseaux de neurones convolutifs", "Captum, Grad-CAM, PyTorch", "Avancé", 6],
  ["Détection de somnolence du conducteur en temps réel", "MediaPipe, OpenCV, Raspberry Pi OS", "Intermédiaire", 5],
  ["Apprentissage par renforcement pour gestion de stocks", "Gymnasium, Stable-Baselines3, SimPy", "Avancé", 6],
  ["Correction orthographique et grammaticale en français", "LanguageTool, spaCy, FastAPI", "Débutant", 4],
  ["Détection de deepfakes vidéo", "PyTorch, OpenCV, timm", "Avancé", 6],
  ["Prédiction de maintenance prédictive sur machines tournantes", "River, scikit-learn, InfluxDB", "Intermédiaire", 5],
  ["Génération de données synthétiques tabulaires", "SDV, CTGAN, pandas", "Avancé", 6],
  ["Moteur de questions-réponses sur base documentaire interne", "Haystack, Elasticsearch, Llama.cpp", "Intermédiaire", 5],
];

const AGENTS = [
  ["Agent autonome de résolution d'incidents IT", "LangGraph, Ollama, Zabbix API", "Avancé", 6],
  ["Assistant conversationnel RAG sur documentation technique", "LlamaIndex, Qdrant, Ollama", "Intermédiaire", 5],
  ["Agent de revue de code automatisée sur pull requests", "CrewAI, Ollama, GitLab API", "Avancé", 6],
  ["Orchestrateur multi-agents pour veille concurrentielle", "AutoGen, Ollama, Scrapy", "Avancé", 6],
  ["Agent de génération et exécution de tests automatisés", "LangChain, Playwright, Ollama", "Avancé", 6],
  ["Copilote de requêtes SQL en langage naturel", "Vanna.ai, DuckDB, Ollama", "Intermédiaire", 5],
  ["Agent de triage automatique des tickets support", "LangGraph, Ollama, PostgreSQL", "Intermédiaire", 5],
  ["Assistant de recherche académique avec citations vérifiées", "LlamaIndex, Zotero API, Ollama", "Intermédiaire", 5],
  ["Agent de surveillance et synthèse de flux réglementaires", "LangChain, Chroma, Ollama", "Intermédiaire", 5],
  ["Framework d'évaluation de la qualité des agents", "DeepEval, Ragas, Langfuse", "Avancé", 6],
  ["Agent de remplissage automatique de formulaires web", "Playwright, LangChain, Ollama", "Intermédiaire", 5],
  ["Assistant de préparation aux entretiens techniques", "Ollama, LangChain, Streamlit", "Débutant", 4],
  ["Agent de génération de documentation à partir du code source", "LangChain, tree-sitter, Ollama", "Intermédiaire", 5],
  ["Système multi-agents de simulation de négociation commerciale", "AutoGen, Mesa, Ollama", "Avancé", 6],
  ["Agent de détection et correction de données incohérentes", "LangGraph, Great Expectations, Ollama", "Avancé", 6],
  ["Copilote d'administration Kubernetes en langage naturel", "LangChain, kubectl, Ollama", "Avancé", 6],
  ["Agent de résumé et action sur courriels entrants", "LangChain, IMAP, Ollama", "Intermédiaire", 4],
  ["Protocole d'outillage d'agents via Model Context Protocol", "MCP SDK, Ollama, FastAPI", "Avancé", 6],
  ["Agent de génération de tableaux de bord analytiques", "LangChain, Apache Superset, Ollama", "Intermédiaire", 5],
  ["Assistant pédagogique adaptatif pour apprentissage du code", "Ollama, LangGraph, Jupyter", "Intermédiaire", 5],
  ["Agent de curation et classement de candidatures", "LangChain, Qdrant, Ollama", "Intermédiaire", 5],
  ["Mémoire à long terme pour agents conversationnels", "Mem0, Qdrant, Ollama", "Avancé", 6],
  ["Agent de rédaction de rapports d'audit technique", "CrewAI, Ollama, Pandoc", "Intermédiaire", 5],
  ["Système d'agents pour tests de charge intelligents", "LangChain, k6, Ollama", "Avancé", 6],
  ["Agent de traduction et localisation de logiciels", "LangChain, Weblate, Ollama", "Intermédiaire", 5],
  ["Orchestration d'agents sur workflows métier", "n8n, LangChain, Ollama", "Intermédiaire", 5],
  ["Agent de détection de vulnérabilités dans les dépendances", "LangChain, OSV-Scanner, Ollama", "Avancé", 6],
  ["Assistant vocal local pour poste de travail", "Whisper, Piper, Ollama", "Intermédiaire", 5],
  ["Agent de génération de données de test réalistes", "LangChain, Faker, Ollama", "Débutant", 4],
  ["Garde-fous et filtrage de sortie des agents", "Guardrails-AI, NeMo Guardrails, Ollama", "Avancé", 6],
  ["Agent de planification de sprints à partir du backlog", "LangGraph, Jira API, Ollama", "Intermédiaire", 5],
  ["Comparateur automatisé de modèles de langage locaux", "Ollama, lm-evaluation-harness, MLflow", "Intermédiaire", 5],
  ["Agent d'analyse de journaux applicatifs", "LangChain, Loki, Ollama", "Avancé", 6],
  ["Système RAG multimodal texte et image", "LlamaIndex, CLIP, Qdrant", "Avancé", 6],
  ["Agent de migration de code entre frameworks", "LangChain, tree-sitter, Ollama", "Avancé", 6],
  ["Assistant de conformité RGPD sur bases de données", "LangChain, PostgreSQL, Ollama", "Intermédiaire", 5],
  ["Agent de génération de scénarios de test de sécurité", "CrewAI, OWASP ZAP, Ollama", "Avancé", 6],
  ["Observabilité et traçage des chaînes d'agents", "Langfuse, OpenTelemetry, Ollama", "Avancé", 6],
  ["Agent de synthèse de réunions enregistrées", "Whisper, LangChain, Ollama", "Intermédiaire", 4],
  ["Marketplace interne d'outils pour agents", "MCP SDK, FastAPI, PostgreSQL", "Avancé", 6],
];

const DEVOPS = [
  ["Plateforme GitOps de déploiement continu multi-environnements", "ArgoCD, Kubernetes, Helm, Git", "Avancé", 6],
  ["Chaîne CI/CD complète pour microservices", "GitLab CI, Docker, Kubernetes, Helm", "Intermédiaire", 5],
  ["Infrastructure as Code multi-cloud reproductible", "Terraform, OpenTofu, Ansible", "Avancé", 6],
  ["Plateforme d'observabilité unifiée logs, métriques et traces", "Prometheus, Loki, Tempo, Grafana", "Avancé", 6],
  ["Automatisation de la configuration de parcs serveurs", "Ansible, Molecule, Vagrant", "Intermédiaire", 5],
  ["Service mesh et gestion du trafic inter-services", "Istio, Envoy, Kubernetes", "Avancé", 6],
  ["Registre d'artefacts et gestion des dépendances internes", "Harbor, Nexus, Docker", "Intermédiaire", 5],
  ["Tests de charge automatisés intégrés au pipeline", "k6, Grafana, GitLab CI", "Intermédiaire", 5],
  ["Gestion centralisée des secrets applicatifs", "HashiCorp Vault, External Secrets, Kubernetes", "Avancé", 6],
  ["Auto-scaling événementiel de charges de travail", "KEDA, Kubernetes, Kafka", "Avancé", 6],
  ["Plateforme de déploiement progressif canary et blue-green", "Argo Rollouts, Flagger, Kubernetes", "Avancé", 6],
  ["Environnements de développement éphémères à la demande", "Kubernetes, Devcontainers, Tilt", "Intermédiaire", 5],
  ["Supervision de coûts d'infrastructure Kubernetes", "OpenCost, Prometheus, Grafana", "Intermédiaire", 5],
  ["Pipeline de build reproductible et cache distribué", "Bazel, BuildKit, GitLab CI", "Avancé", 6],
  ["Sauvegarde et restauration de clusters Kubernetes", "Velero, MinIO, Kubernetes", "Intermédiaire", 5],
  ["Orchestration de traitements batch planifiés", "Apache Airflow, Kubernetes, PostgreSQL", "Intermédiaire", 5],
  ["Plateforme de conteneurisation d'applications héritées", "Docker, Podman, Buildah", "Débutant", 4],
  ["Chaos engineering et tests de résilience", "Chaos Mesh, LitmusChaos, Kubernetes", "Avancé", 6],
  ["Politique de conformité as code sur clusters", "OPA Gatekeeper, Kyverno, Kubernetes", "Avancé", 6],
  ["Passerelle d'API interne avec authentification", "Kong, Traefik, Keycloak", "Intermédiaire", 5],
  ["Plateforme de journalisation à haute volumétrie", "Fluent Bit, OpenSearch, Kubernetes", "Avancé", 6],
  ["Automatisation du provisionnement réseau", "Terraform, Netbox, Ansible", "Avancé", 6],
  ["Portail développeur et catalogue de services", "Backstage, PostgreSQL, Kubernetes", "Avancé", 6],
  ["Migration d'une monolithe vers des microservices conteneurisés", "Docker, Kubernetes, Kafka", "Avancé", 6],
  ["Gestion de configuration applicative dynamique", "Consul, Vault, Kubernetes", "Intermédiaire", 5],
  ["Pipeline de livraison pour applications mobiles", "Fastlane, GitLab CI, Docker", "Intermédiaire", 5],
  ["Base de données en haute disponibilité sur Kubernetes", "CloudNativePG, PostgreSQL, Kubernetes", "Avancé", 6],
  ["Automatisation de la gestion des certificats TLS", "cert-manager, Let's Encrypt, Kubernetes", "Intermédiaire", 4],
  ["Tableau de bord DORA metrics pour équipes de développement", "Grafana, PostgreSQL, GitLab API", "Intermédiaire", 5],
  ["Plateforme serverless auto-hébergée", "Knative, OpenFaaS, Kubernetes", "Avancé", 6],
  ["Gestion multi-tenant d'un cluster partagé", "Capsule, Kubernetes, RBAC", "Avancé", 6],
  ["Automatisation des runbooks d'exploitation", "Ansible, Rundeck, Prometheus", "Intermédiaire", 5],
  ["Détection de dérive de configuration d'infrastructure", "Driftctl, Terraform, GitLab CI", "Intermédiaire", 5],
  ["Cluster Kubernetes en périphérie sur matériel contraint", "K3s, Flux, Raspberry Pi OS", "Intermédiaire", 5],
  ["Passerelle de messagerie asynchrone résiliente", "RabbitMQ, Kafka, Kubernetes", "Avancé", 6],
  ["Automatisation de la mise à jour des dépendances", "Renovate, GitLab CI, Docker", "Débutant", 4],
  ["Plateforme d'exécution de tests end-to-end parallélisés", "Playwright, Selenium Grid, Kubernetes", "Intermédiaire", 5],
  ["Supervision synthétique de parcours utilisateurs", "Blackbox Exporter, Grafana, Playwright", "Intermédiaire", 4],
  ["Gestion du cycle de vie des images de conteneurs", "Trivy, Harbor, Kubernetes", "Intermédiaire", 5],
  ["Interconnexion multi-clusters et fédération", "Cilium Cluster Mesh, Submariner, Kubernetes", "Avancé", 6],
];

const CYBER = [
  ["Centre opérationnel de sécurité complet auto-hébergé", "Wazuh, OpenSearch, TheHive", "Avancé", 6],
  ["Détection d'intrusions réseau par analyse comportementale", "Suricata, Zeek, Elasticsearch", "Avancé", 6],
  ["Plateforme de gestion et corrélation d'incidents", "TheHive, Cortex, MISP", "Avancé", 6],
  ["Automatisation des réponses à incident", "Shuffle, TheHive, Wazuh", "Avancé", 6],
  ["Scanner de vulnérabilités d'infrastructure automatisé", "OpenVAS, Nmap, PostgreSQL", "Intermédiaire", 5],
  ["Analyse de sécurité des applications web", "OWASP ZAP, Nuclei, Burp Suite Community", "Intermédiaire", 5],
  ["Plateforme de renseignement sur les menaces", "MISP, OpenCTI, Python", "Avancé", 6],
  ["Sécurisation de la chaîne d'approvisionnement logicielle", "Sigstore, Syft, Grype", "Avancé", 6],
  ["Analyse statique de code et détection de secrets", "Semgrep, Gitleaks, TruffleHog", "Intermédiaire", 5],
  ["Durcissement automatisé de systèmes Linux", "OpenSCAP, Lynis, Ansible", "Intermédiaire", 5],
  ["Honeypot distribué et analyse des attaques", "T-Pot, Cowrie, Elasticsearch", "Intermédiaire", 5],
  ["Analyse de logiciels malveillants en environnement isolé", "Cuckoo Sandbox, YARA, Radare2", "Avancé", 6],
  ["Gestion des identités et accès fédérés", "Keycloak, OpenLDAP, OAuth2 Proxy", "Intermédiaire", 5],
  ["Détection de menaces sur conteneurs à l'exécution", "Falco, Tetragon, Kubernetes", "Avancé", 6],
  ["Audit de sécurité de clusters Kubernetes", "kube-bench, kube-hunter, Trivy", "Intermédiaire", 5],
  ["Analyse forensique de postes compromis", "Autopsy, Volatility, Sleuth Kit", "Avancé", 6],
  ["Plateforme de simulation de phishing et sensibilisation", "GoPhish, Postfix, PostgreSQL", "Intermédiaire", 4],
  ["Architecture zero trust pour accès distant", "WireGuard, Pomerium, Keycloak", "Avancé", 6],
  ["Chiffrement de bout en bout pour messagerie interne", "Signal Protocol, libsodium, Matrix", "Avancé", 6],
  ["Détection de fuites de données sortantes", "Suricata, Zeek, OpenSearch", "Avancé", 6],
  ["Pare-feu applicatif web configurable", "ModSecurity, Coraza, OWASP CRS", "Intermédiaire", 5],
  ["Gestion du cycle de vie des certificats internes", "step-ca, cert-manager, Vault", "Intermédiaire", 5],
  ["Tests d'intrusion automatisés et rapport reproductible", "Metasploit Framework, Nmap, Nuclei", "Avancé", 6],
  ["Sécurité des API et détection d'abus", "Kong, OpenAPI, ModSecurity", "Intermédiaire", 5],
  ["Analyse de sécurité d'applications mobiles Android", "MobSF, Frida, apktool", "Avancé", 6],
  ["Plateforme de gestion des vulnérabilités priorisées", "DefectDojo, Trivy, OSV-Scanner", "Intermédiaire", 5],
  ["Détection d'usurpation dans les réseaux sans fil", "Kismet, Aircrack-ng, Scapy", "Intermédiaire", 5],
  ["Journalisation inviolable et intégrité des traces", "Auditd, Wazuh, Sigstore", "Avancé", 6],
  ["Sécurisation des systèmes industriels et protocoles OT", "Suricata, Conpot, Zeek", "Avancé", 6],
  ["Analyse de la surface d'attaque externe", "Amass, Subfinder, Nuclei", "Intermédiaire", 5],
  ["Détection de mouvements latéraux en environnement Windows", "Wazuh, Sysmon, Velociraptor", "Avancé", 6],
  ["Plateforme de chasse aux menaces", "Velociraptor, OpenSearch, Sigma", "Avancé", 6],
  ["Protection des données au repos et gestion des clés", "LUKS, Vault, age", "Intermédiaire", 5],
  ["Détection d'attaques par déni de service applicatif", "Nginx, Suricata, Prometheus", "Intermédiaire", 5],
  ["Conformité et rapport d'audit automatisé", "OpenSCAP, Wazuh, Grafana", "Intermédiaire", 5],
  ["Analyse de sécurité des images de conteneurs", "Trivy, Grype, Clair", "Débutant", 4],
  ["Détection de comportements anormaux par apprentissage", "PyOD, Zeek, OpenSearch", "Avancé", 6],
  ["Gestion des accès privilégiés et enregistrement de sessions", "Teleport, Keycloak, PostgreSQL", "Avancé", 6],
  ["Sécurisation d'une chaîne CI/CD contre les compromissions", "Sigstore, Semgrep, GitLab CI", "Avancé", 6],
  ["Anonymisation et pseudonymisation de données sensibles", "ARX, Faker, PostgreSQL", "Intermédiaire", 5],
];

const DATA = [
  ["Entrepôt de données analytique moderne auto-hébergé", "DuckDB, dbt, Apache Superset", "Intermédiaire", 5],
  ["Pipeline ELT orchestré pour sources hétérogènes", "Airbyte, dbt, Apache Airflow", "Intermédiaire", 5],
  ["Lakehouse avec gestion de versions de données", "Apache Iceberg, Trino, MinIO", "Avancé", 6],
  ["Traitement de flux temps réel à grande échelle", "Apache Flink, Kafka, ClickHouse", "Avancé", 6],
  ["Plateforme de qualité et validation de données", "Great Expectations, Soda Core, Airflow", "Intermédiaire", 5],
  ["Catalogue de données et traçabilité des transformations", "OpenMetadata, dbt, PostgreSQL", "Avancé", 6],
  ["Tableau de bord décisionnel pour direction commerciale", "Metabase, PostgreSQL, dbt", "Débutant", 4],
  ["Analyse géospatiale de données de mobilité urbaine", "PostGIS, GeoPandas, QGIS", "Intermédiaire", 5],
  ["Migration d'un système décisionnel vers une architecture ouverte", "Trino, dbt, MinIO", "Avancé", 6],
  ["Base de données orientée colonnes pour analyse à haute cardinalité", "ClickHouse, Grafana, Kafka", "Avancé", 6],
  ["Analyse de la performance commerciale par cohortes", "DuckDB, pandas, Streamlit", "Intermédiaire", 4],
  ["Plateforme de reporting réglementaire automatisé", "dbt, Airflow, Apache Superset", "Intermédiaire", 5],
  ["Détection de doublons et réconciliation d'identités", "Splink, DuckDB, pandas", "Avancé", 6],
  ["Analyse de paniers d'achat et règles d'association", "mlxtend, pandas, Metabase", "Débutant", 4],
  ["Entrepôt de séries temporelles pour supervision industrielle", "TimescaleDB, Grafana, Telegraf", "Intermédiaire", 5],
  ["Analyse de sentiment et de tendances sur données publiques", "spaCy, DuckDB, Streamlit", "Intermédiaire", 4],
  ["Plateforme de partage de jeux de données ouverts", "CKAN, PostgreSQL, MinIO", "Intermédiaire", 5],
  ["Modélisation dimensionnelle d'un domaine métier complexe", "dbt, PostgreSQL, dbt-docs", "Intermédiaire", 5],
  ["Analyse prédictive du churn client", "scikit-learn, dbt, Metabase", "Intermédiaire", 5],
  ["Pipeline de traitement de données massives par lots", "Apache Spark, Delta Lake, MinIO", "Avancé", 6],
  ["Observabilité des pipelines et détection de régressions", "OpenLineage, Marquez, Airflow", "Avancé", 6],
  ["Analyse de la logistique et optimisation de tournées", "OR-Tools, GeoPandas, Streamlit", "Avancé", 6],
  ["Tableau de bord de suivi des indicateurs hospitaliers", "Metabase, PostgreSQL, dbt", "Intermédiaire", 5],
  ["Analyse de journaux web et parcours utilisateurs", "ClickHouse, Grafana, Kafka", "Intermédiaire", 5],
  ["Plateforme de features pour modèles d'apprentissage", "Feast, Redis, PostgreSQL", "Avancé", 6],
  ["Analyse de la consommation énergétique par segmentation", "scikit-learn, DuckDB, Apache Superset", "Intermédiaire", 5],
  ["Automatisation de la collecte de données web", "Scrapy, Playwright, PostgreSQL", "Intermédiaire", 4],
  ["Analyse de données d'enquête et redressement statistique", "R, pandas, Quarto", "Intermédiaire", 5],
  ["Entrepôt de données pour établissement d'enseignement", "dbt, PostgreSQL, Metabase", "Intermédiaire", 5],
  ["Analyse de la fraude par graphes de relations", "Neo4j Community, NetworkX, Cypher", "Avancé", 6],
  ["Plateforme de tests A/B et analyse statistique", "GrowthBook, PostgreSQL, Python", "Intermédiaire", 5],
  ["Analyse de la performance financière et prévisions", "Prophet, DuckDB, Apache Superset", "Intermédiaire", 5],
  ["Traitement et analyse de documents non structurés à grande échelle", "Apache Tika, Elasticsearch, Airflow", "Avancé", 6],
  ["Gouvernance et contrôle d'accès aux données sensibles", "Apache Ranger, Trino, Keycloak", "Avancé", 6],
  ["Analyse de données de capteurs agricoles", "TimescaleDB, Grafana, pandas", "Intermédiaire", 5],
  ["Rapports analytiques reproductibles et versionnés", "Quarto, DuckDB, Git", "Débutant", 4],
  ["Plateforme d'analyse en libre-service pour métiers", "Apache Superset, Trino, dbt", "Intermédiaire", 5],
  ["Détection d'anomalies sur indicateurs métier", "Prophet, PyOD, Grafana", "Intermédiaire", 5],
  ["Analyse du trafic réseau pour dimensionnement", "ClickHouse, Zeek, Grafana", "Avancé", 6],
  ["Modernisation d'un processus de reporting manuel", "dbt, Airflow, Metabase", "Débutant", 4],
];

const DOMAINS = [
  { key: "ai", label: "Intelligence Artificielle", rows: AI },
  { key: "agents", label: "AI Agents", rows: AGENTS },
  { key: "devops", label: "DevOps", rows: DEVOPS },
  { key: "cyber", label: "Cybersécurité", rows: CYBER },
  { key: "data", label: "Data Analysis", rows: DATA },
];

export const SUJETS = DOMAINS.flatMap((d, di) =>
  d.rows.map((r, i) => ({
    id: "PFE-" + String(di * 40 + i + 1).padStart(3, "0"),
    domain: d.key,
    domainLabel: d.label,
    title: r[0],
    stack: r[1],
    level: r[2],
    months: r[3],
  }))
);

export const DOMAIN_LIST = DOMAINS.map((d) => ({ key: d.key, label: d.label, count: d.rows.length }));
export const LEVELS = ["Débutant", "Intermédiaire", "Avancé"];
